NullVoxPopuli/ember-resources

README.md
tests/unit/use-resource-test.ts

chore(tests): demo example of Issue#48

---

addon/-private/resources/function-runner.ts
addon/-private/use-function.ts
addon/-private/use-resource.ts
addon/index.ts
tests/unit/use-function-test.ts

BREAKING CHANGE: useFunction is no longer an alias of useResource

feat(useFunction): now supports an initialValue param

---

.github/workflows/ci.yml

Resolves: https://github.com/NullVoxPopuli/ember-resources/issues/82

chore(internal): re-enable ember-canary testing

---

addon/-private/resources/simple.ts
addon/-private/types.ts
tests/unit/lifecycle-resource-test.ts
tests/unit/resource-test.ts
tests/unit/types-test.ts

Resolves https://github.com/NullVoxPopuli/ember-resources/issues/108

fix(issue#108): loosen the constraint on what named arguments are

---

.github/workflows/ci.yml
.github/workflows/lint.yml
README.md
ember-resources/package.json
ember-resources/src/-private/resources/function-runner.ts
ember-resources/src/-private/tracked-function.ts
ember-resources/src/index.ts
testing/ember-app/config/ember-try.js
testing/ember-app/tests/unit/tracked-function-test.ts
yarn.lock

new resource: `trackedFunction`
it is arg-less, but still receives the previous value if you need
to manage the state of repeated calls to the function.

feat: add trackedFunction

---

ember-resources/package.json
testing/ember-concurrency-v1/tsconfig.json

type-declarations could not be found.
This resolves https://github.com/NullVoxPopuli/ember-resources/issues/306

fix(types): compat with TS 4.5.1

---

ember-resources/package.json
ember-resources/src/-private/ember-concurrency.ts
testing/ember-app/app/config/environment.d.ts
testing/ember-app/tests/test-helper.ts
testing/ember-app/tests/unit/use-task-test.ts

Resolves: https://github.com/NullVoxPopuli/ember-resources/issues/368
ember-concurrency@v1 needs extra hacks to get the same reactivity that we get for free in ember-concurrency@v2

provide better support for ember-concurrency@v1

---

ember-resources/package.json
yarn.lock

Reverts NullVoxPopuli/ember-resources#302

Revert "chore(deps): update semantic-release monorepo (major)"

---

ember-resources/package.json
ember-resources/src/util/remote-data.ts
pnpm-lock.yaml
testing/ember-app/.eslintignore
testing/ember-app/package.json
testing/ember-app/public/mockServiceWorker.js
testing/ember-app/tests/msw.ts
testing/ember-app/tests/utils/remote-data/js-test.ts

https://wycats.github.io/polaris-sketchwork/reactivity.html#example
Supports

Create example RemoteData resource from the Polaris examples

---

ember-resources/src/deprecated-in-v4/ember-concurrency.ts
ember-resources/src/util/ember-concurrency.ts
package.json
pnpm-lock.yaml
testing/ember-app/package.json
testing/ember-app/public/mockServiceWorker.js

chore(internal): single command v2 addon development

---

ember-resources/src/core/function-based/manager.ts
ember-resources/src/core/function-based/types.ts
testing/ember-app/tests/utils/function-resource/js-test.ts
testing/ember-app/tests/utils/function-resource/rendering-test.ts

Here is an idea, I mentioned earlier.
I thought I give it a spin to make the owner available to function based resources (class-based resources already have access to it).
This is incomplete. Was wondering if I'm on the right track here. Would add more tests then (at least a rendering test), what else?

feat: Make owner available to function-based resource

---

ember-resources/src/util/function.ts
testing/ember-app/tests/utils/function-resource/rendering-test.ts
testing/ember-app/tests/utils/function/rendering-test.ts

Initial implementation and exploration here: https://github.com/NullVoxPopuli/ember-resources/pull/559/files
by [@velrest](https://github.com/velrest) :tada:

feat(trackedFunction): add a retry method

---

.changeset/afraid-cherries-type.md
ember-resources/src/util/map.ts

fix: typo in map.ts error message

---

.changeset/hungry-waves-kiss.md
ember-resources/.prettierignore
ember-resources/package.json
ember-resources/src/core/class-based/resource.ts
ember-resources/src/util/function.ts
pnpm-lock.yaml
testing/ember-app/.eslintrc.js
testing/ember-app/app/components/util/function.gts
testing/ember-app/package.json
testing/ember-app/tests/utils/function/js-test.ts
testing/ember-app/tests/utils/function/rendering-test.gts
testing/ember-app/tests/utils/function/state-test.ts
testing/ember-app/tests/utils/keep-latest/js-test.ts
testing/ember-app/tests/utils/keep-latest/rendering-test.gts
testing/ember-app/tsconfig.json

Supersedes: https://github.com/NullVoxPopuli/ember-resources/pull/683 (and see #683 for all the discussion, conversation, and debugging that lead to this PR)
Huge thanks to @lolmaus for doing 99% of this work!!!

Improvements to trackedFunction and State

---

.changeset/chilly-keys-kick.md
ember-resources/package.json
ember-resources/src/util/function.ts
pnpm-lock.yaml
test-app/package.json

Supersedes https://github.com/NullVoxPopuli/ember-resources/pull/823

ember-async-data@v1 is out, so we can bump

---

.changeset/mean-moons-grab.md
ember-resources/src/util/ember-concurrency.ts
testing/ember-app/tests/utils/ember-concurrency/js-test.ts

fix: incorrect value returned when last task was dropped

---

.changeset/mean-moons-grab.md
ember-resources/src/util/ember-concurrency.ts
test-app/tests/utils/ember-concurrency/js-test.ts

fix: #835 incorrect value returned when last task was dropped

---

README.md

I guess ending function definition with a comma in class - is a typo, isn't it ?

minor typo in the readme file

---

.github/workflows/ci.yml

Addresses the issue with floating deps

Use pnpm-args directly

---

ember-resources/src/util/function.ts

the `on` modifier was not imported, no use of `this` outside of a class, need to use `use`...

fix: bugs in trackedFunction docs

---

ember-resources/src/core/use.ts

Fixes a small typo in the docs.

fix: typo in use doc

---

docs/typedoc.utils.config.json

docs: Update typedoc.utils.config.json continuation of #1036

---

docs/typedoc.config.json

Remove API Reference docs' sidebar

---

package.json
pnpm-lock.yaml

https://github.com/ef4/lerna-changelog/pull/8
This blocked the v7 release yesterday, here https://github.com/NullVoxPopuli/ember-resources/actions/runs/7482171149/job/20365200936
and  I reported the issue here: https://github.com/embroider-build/release-plan/issues/46

Use fix for release-plan from: https://github.com/ef4/lerna-changelog/pull/8

---

package.json
pnpm-lock.yaml

Testing out: https://github.com/embroider-build/release-plan/pull/47

Update release-plan for https://github.com/embroider-build/release-plan/pull/47

---

.github/workflows/ci.yml
MIGRATIONS.md
codemod/.eslintrc.cjs
codemod/.prettierrc.cjs
codemod/bin.mjs
codemod/package.json
codemod/pnpm-lock.yaml
codemod/src/all.js
codemod/src/logging.d.ts
codemod/src/logging.js
codemod/src/nearest-package-json.js
codemod/src/utils.js
codemod/src/v6-to-v7/imports.changeImportPaths.test.ts
codemod/src/v6-to-v7/imports.changeNamedImport.test.ts
codemod/src/v6-to-v7/imports.js
codemod/src/v6-to-v7/index.js
codemod/src/v6-to-v7/replacements.js
codemod/tsconfig.json
package.json
pnpm-workspace.yaml
test-app/config/environment.js

once published
```bash
npx ember-resources-codemod
```

Add v6 to v7 codemod
