NullVoxPopuli/ember-resources

README.md

- All code snippets have all `ember-resources` imports present

doc(#87): copyable examples

---

README.md

- To give an example of how to use this ember-resources
- To make sure people are not reinventing the wheel
- To encourage people to create their own addons

doc(#90): cross link other addons

---

.github/workflows/ci.yml
.gitignore
addon/-private/resources/ember-concurrency-task.ts
config/ember-try.js
package-lock.json
package.json
tests/unit/use-task-test.ts

idk what happened to the ec@1 testing... but this brings it back and fixes an issue encountered only in ember-concurrency@v1 where _not_ accessing the isRunning property on the task means that `value` won't update when the task finally resolves.

fix(useTask): re-test against ember-concurrency@v1

---

ember-resources/src/-private/resources/function-runner.ts

It seems that we didn't have to call `Promise.resolve` twice, and we
also could just resolve the value in either case of being a plain value
or a promise.
Seems to work locally with tests, but I will be depending on ci testing

refactor(function-runner): Refactored some Promise lines

---

ember-resources/package.json
testing/ember-app/config/ember-try.js
testing/ember-app/package.json
yarn.lock

See explanation: https://github.com/NullVoxPopuli/ember-resources/issues/403#issuecomment-1048404119
tldr: peerDeps are the only way to guarantee that modern packagers
only load one version (specified by the consumer)
Interesting discovery while testing this:
- locally, the embroider try scenarios succeed :upside_down_face:

fix: `@ember/test-waiters` must be a peer dependency

---

.github/workflows/ci.yml
ember-resources/package.json
ember-resources/rollup.config.js
ember-resources/src/index.ts
testing/build/expected-output-files.txt
testing/build/package.json
testing/build/test.js
yarn.lock

Just kidding - my local environment had stale deps.
My kingdom for a generic dependency lint :sweat_smile: 
Gonna keep the test though, because I have low trust in my rollup abilities atm
-----------------------
Additionally, it seems there are type errors in consuming projects, so I'm going to try to fix that in here

fix: useTask's types not available in some consuming apps

---

ember-resources/package.json

Follow up to https://github.com/NullVoxPopuli/ember-resources/pull/407#issuecomment-1051102858

fix: Move `@ember/test-waiters` to peerDependencies

---

docs/package.json
ember-resources/package.json
pnpm-lock.yaml

Reverts NullVoxPopuli/ember-resources#434
I've added more restrictions on merging to the `main` branch due to this oversight.
It turns out, if the branch goes green before CI boots up, renovate will just merge things if nothing is blocking the PR :see_no_evil:

Revert "chore(deps): update dependency typescript to v4.6.4"

---

.npmrc
ember-resources/src/util/function-resource.ts
ember-resources/src/util/remote-data.ts
pnpm-lock.yaml
testing/ember-app/tests/utils/function-resource/rendering-test.ts
testing/ember-app/tests/utils/remote-data/rendering-test.ts

In order to use RemoteData as template-resource, we need
_another helper manager_, and we need to register it as well.
This ends up resulting in _nested_ helper-manager invocation for a
single helper-invocation call.
Resolves: https://github.com/NullVoxPopuli/ember-resources/issues/486
Todo

fix(RemoteData, function-resource): wrapped template usage

---

.gitignore
ember-resources/package.json
ember-resources/src/util/debounce.ts
ember-resources/tsconfig.json
package.json
pnpm-lock.yaml
testing/ember-app/tests/utils/debounce/js-test.ts
testing/ember-app/tsconfig.json

Implements: https://github.com/NullVoxPopuli/ember-resources/issues/506

feat: new util: debounce

---

ember-resources/src/util/function-resource.ts
ember-resources/src/util/remote-data.ts
package.json
pnpm-lock.yaml
testing/ember-app/app/config/environment.d.ts
testing/ember-app/config/environment.js
testing/ember-app/package.json
testing/ember-app/tests/msw.ts
testing/ember-app/tests/utils/function-resource/js-test.ts
testing/ember-app/tests/utils/function-resource/rendering-test.ts

Resolves an issue where, when a function-resource is directly used in a template,
the lifecycle of invoking and running cleanup was incorrect when wrapped
in an if statement (or any conditional rendering situation).  Now, when
a resource used within `{{ ... }}` is removed from the render tree, the
cleanup hook will run.

fix(function-resource): lifecycle fixes

---

DOCS.md
ember-resources/src/util/function-resource.ts
testing/ember-app/tests/utils/function-resource/clock-test.ts
testing/ember-app/tests/utils/function-resource/js-test.ts
testing/ember-app/tests/utils/function-resource/rendering-test.ts

feat(function-resource): support encapsulated tracked state
This is based on ideas from https://wycats.github.io/polaris-sketchwork/reactivity.html
Where a function-based resource _may_ return an arrow function instead
of a non-function-value. This allows the function-based resource to
conusme and update its own tracked state without invalidating itself.
Previously, in order for function-based resources to have their own
tracked state, an object had to be returned, and it was up to the
consumer to consume that tracked state via property access.
With this arrow-function return, we can provide a single reactive value
via the resource as well as encapsulated state.

function-resource refinements

---

ember-resources/src/util/map.ts

Fixes a typo in the import location for one of the examples for the `map` util.

chore(docs): Fix typo in `map` example

---

ember-resources/package.json
ember-resources/src/index.ts
ember-resources/src/util/cell.ts
testing/ember-app/tests/utils/cell/rendering-test.ts

feat(util): add cell

---

ember-resources/src/util/keep-latest.ts
testing/ember-app/tests/utils/keep-latest/js-test.ts
testing/ember-app/tests/utils/keep-latest/rendering-test.gts

when - keepLatest _when_ this is true.
until - kinda means the opposite. So this word is a bug.

fix(keepLatest): use consistent condition name

---

ember-resources/src/util/cell.ts
testing/ember-app/tests/utils/cell/rendering-test.gts

in typescript / glint,  `cell` will now infer the type.
when you use `cell` with no initial value, you'll want to explicitly declare the type, as is demonstrated in the `it works` cell rendering test

fix(cell): improve typings of the cell utility

---

ember-resources/src/util/keep-latest.ts
testing/ember-app/tests/utils/keep-latest/js-test.ts

The logic for calculating `isEmpty` was incorrect for a few cases. 
It needs to return true for:
- empty arrays
- objects that are either null or have no keys (was opposite)
- any other value that is falsey (was opposite. Also accounting for 0 now)
See updated tests for the various cases

Fix isEmpty logic in keepLatest

---

ember-resources/CHANGELOG.md

The example in the original had some bugs. As it initiated a new `setInterval` on every compute it just keep adding every time Ember recomputed the helper. It also would register a destructor on every compute.
This change uses a WeakMap to track the intervals and only registers a destructor once.

Fix polling helper example in CHANGELOG

---

.github/workflows/push-dist.yml
ember-resources/package.json

This uses an action I created: https://github.com/kategengler/put-built-npm-package-contents-on-branch
I added a `prepack` script in the ember-resources dir so that the defaults of the action would just work, otherwise it could be done before the action in the workflow. 
This requires a `token` to be passed that has write access to the contents of the repo (either `secrets.GITHUB_TOKEN` if you enable that token having write access or a correctly set up personal access token).
The action has several inputs for customization https://github.com/kategengler/put-built-npm-package-contents-on-branch#inputs

Push the built contents of the npm package to a branch on every commit to main

---

.changeset/curvy-frogs-sin.md
.github/workflows/ci.yml

Requires: https://github.com/NullVoxPopuli/ember-resources/pull/714
TODO:
- read through https://github.com/emberjs/rfcs/pull/730 to determine what should be the semver impacts here

Drop older TS as Glint doesn't support it

---

.github/workflows/ci.yml
package.json
patches/@changesets__assemble-release-plan@5.2.3.patch
pnpm-lock.yaml

I've applied the patch from:
https://gist.github.com/ndaba1/b63f6a30b8f6211a156f835480044d27

Due to: https://github.com/changesets/changesets/issues/835

---

.changeset/hungry-waves-kiss.md
ember-resources/src/util/function.ts

A couple have provided feedback, and for DX, folks agree that having more aliases for representing promise state is preferred

Add aliases to trackedFunction

---

.changeset/many-brooms-turn.md
ember-resources/src/util/ember-concurrency.ts
test-app/tests/utils/ember-concurrency/js-test.ts

This PR fixes the issue described at https://github.com/NullVoxPopuli/ember-resources/issues/793
The issue: If the task was called multiple times and the last returned value was `null` or `undefined`, then `trackedTask` will return the previous value instead of the current one.

fix: `trackedTask` must return correct last value

---

ember-resources/src/util/ember-concurrency.ts

Fix for #903: Rewrite `trackedTask` documentation to ember-concurrency's new async arrow API:

docs: Fix type issue in docs

---

.changeset/neat-apples-shout.md
ember-resources/src/util/function.ts
test-app/tests/utils/function/rendering-test.gts
test-app/tests/utils/function/timing-test.gts

Investigation of https://github.com/NullVoxPopuli/ember-resources/issues/1010

Add some timing tests for trackedFunction

---

.changeset/sour-coats-shop.md
ember-resources/src/util/keep-latest.ts
ember-resources/type-tests/keep-latest.test.ts

The `undefined` was unnecessary.

Fix keepLatest types

---

ember-resources/src/util/keep-latest.ts
test-app/tests/utils/keep-latest/js-test.ts
test-app/tests/utils/keep-latest/rendering-test.gts

tl;dr:
- use the `value` on the first run of the `keepLatest`, if available (instead of previous, which is always `undefined`)
- add tests clarifying behavior
-----------
The way to provide a default value when the value of keepLatest is false is to use another getter.
This PR adds a couple tests clarifying that behavior:
```ts
class Demo {
@use latest = keepLatest({
value: () => this.data.value?.meta,
when: () => this.data.isLoading,    
})
get theData() {
return this.latest ?? 'default value';
}
}
```
It's important to not do
```js
value: () => this.data.value?.meta ?? {},
```
because that means falsey responses (on `data`), will resolve to `{}`, and cause content flashes.
So to keep the latest value, you want to let the `data` response be what it actually is.
In traditional logic, this …

Fix issue with keepLatest and empty values

---

ember-resources/src/util/debounce.ts
ember-resources/src/util/ember-concurrency.ts
ember-resources/src/util/fps.ts
ember-resources/src/util/function.ts
ember-resources/src/util/helper.ts
ember-resources/src/util/keep-latest.ts
ember-resources/src/util/map.ts
ember-resources/src/util/remote-data.ts

[v6]: Deprecate util/* imports

---

ember-resources/src/core/class-based/resource.ts

Closes:
- https://github.com/NullVoxPopuli/ember-resources/issues/1054
- https://github.com/NullVoxPopuli/ember-resources/issues/1056
Replacement: 
- https://github.com/NullVoxPopuli/ember-modify-based-class-resource

Deprecate the class-based Resource, moved to ember-modify-based-class-resource

---

ember-resources/package.json
pnpm-lock.yaml

Due to floating dependencies, a dev-env TS Upgrade, incorrect (for the ember ecosystem) type declarations were created -- using `/// <reference`.
We don't want these, because it breaks expectations of the consumer importing a module containing a ton of `declare module` (or using the `@types` packages).
To fix this, I made a new tool: https://github.com/NullVoxPopuli/fix-bad-declaration-output

Fix declaration output

---

ember-resources/src/function-based/immediate-invocation.ts
ember-resources/src/function-based/manager.ts
test-app/tests/core/function-resource/clock-test.gts
test-app/tests/core/function-resource/js-test.ts
test-app/tests/core/function-resource/js-use-test.gts
test-app/tests/core/function-resource/rendering-test.gts

Without this it's possible to break the public API of `resource`
for example:
```js
const Clock = resource(({ owner }) => {
owner.lookup(...)
});
```
would fail if the resource is constructed in a vanilla class that doesn't have an owner.
This _likely_ will only affect tests.

Require an owner to exist to be wired through to the resource.

---

DOCS.md
docs/docs/ember.md
docs/docs/resources.md
ember-resources/src/function-based/immediate-invocation.ts
ember-resources/src/type-tests/use.test.ts

This also makes migrating away from `resourceFactory` easier once starbeam/formal resource support lands.
However, codemod tools for that migration will still need to support both usages.

Move recommendation of resourceFactory to better align with how TypeScript works

---

ember-resources/src/function-based/types.ts
test-app/tests/core/issue-1128-test.gts

Fix #1128 
Issues:
- `CURRENT` symbol was exposed, and caused interface matching to fail -- it has been cast to a non-symbol via the same lies @runspired is using in ember-data :sweat_smile: 
Unresolved:
- need to better declare the differences in the `use` apis

Fix use types

---

ember-resources/package.json

Now that @glimmer/component v2.0.0 is released (https://www.npmjs.com/package/@glimmer/component?activeTab=versions), I got a warning from pnpm about the peer dependencies of ember-resources

Widen peer range of @glimmer/component

---

.github/workflows/ci.yml
test-app/config/ember-try.js

Also disables testing against beta and canary -- the APIs are stable -- nothing goofy going on beyond potentially tooling-related things that are unrelated to this runtime-only library

Test against 6.4

---

ember-resources/package.json

embroider, auto-import, and ember-cli before them handled virtual deps without a package.json entry.
package.json entries _win_ over virtual deps, so we don't want to declare ember-source or @glimmer/tracking as peers.

Remove ember-source virtualDeps from peerDeps

---

codemod/src/v6-to-v7/imports.changeNamedImport.test.ts
codemod/src/v6-to-v7/imports.js

I had some [lint errors](https://github.com/cardstack/boxel/pull/2777/commits/c50c8b4b4b4915ccd249804ee1d42f48bb8427db) after running the codemod, easily fixed, but I can confirm that running the codemod with this change locally kept the imports along with the semicolon (resulting in no file changes).

Add missing semicolon for kept imports
